## 3D Data Transformation for further modeling

In [19]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
def split_sequence (sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        #find the end of the pattern
        end_ix = i + n_steps
        #check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [8]:
series = np.array([1,2,3,4,5,6,7,8,9])
print(series.shape)

X, y = split_sequence(series, 3)
print(X.shape, y.shape)


print('-------------------')
for i in range(len(X)):
    print(X[i], y[i])

(9,)
(6, 3) (6,)
-------------------
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9


In [39]:
X = X.reshape((X.shape[0], X.shape[1], 1))
X.shape

(6, 3, 1)

We've reached the 3 Dimentional shape needed for an LSTM Model

# Multilayer Perceptrons

### 1. Data preparation

In [9]:
sequence = list()
for i in range(10,210,10):
    sequence.append(i)
print(sequence)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


In [12]:
n_steps = 3
X, y = split_sequence(sequence, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90
[70 80 90] 100
[ 80  90 100] 110
[ 90 100 110] 120
[100 110 120] 130
[110 120 130] 140
[120 130 140] 150
[130 140 150] 160
[140 150 160] 170
[150 160 170] 180
[160 170 180] 190
[170 180 190] 200


### 2. Multilayer Perceptron Model

In [44]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

mlp_model = Sequential()
mlp_model.add(Dense(100, activation='relu', input_dim=n_steps))
mlp_model.add(Dense(1))
mlp_model.compile(optimizer='adam', loss='mse')

mlp_history = mlp_model.fit(X, y , epochs=200, verbose=0)

In [45]:
x_inputs = np.array([180,190,200])
x_inputs = x_inputs.reshape((1, n_steps))

yhat = mlp_model.predict(x_inputs)

print(x_inputs, yhat)

[[180 190 200]] [[219.18059]]
