## 3D Data Transformation for further modeling

In [19]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
def split_sequence (sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        #find the end of the pattern
        end_ix = i + n_steps
        #check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [8]:
series = np.array([1,2,3,4,5,6,7,8,9])
print(series.shape)

X, y = split_sequence(series, 3)
print(X.shape, y.shape)


print('-------------------')
for i in range(len(X)):
    print(X[i], y[i])

(9,)
(6, 3) (6,)
-------------------
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9


In [39]:
X = X.reshape((X.shape[0], X.shape[1], 1))
X.shape

(6, 3, 1)

We've reached the 3 Dimentional shape needed for an LSTM Model

# Multilayer Perceptrons

### 1. Data preparation

In [62]:
sequence = list()
for i in range(10,100,10):
    sequence.append(i)
print(sequence)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [63]:
n_steps = 3
X, y = split_sequence(sequence, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


### 2. Multilayer Perceptron Model

In [64]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

mlp_model = Sequential()
mlp_model.add(Dense(100, activation='relu', input_dim=n_steps))
mlp_model.add(Dense(1))
mlp_model.compile(optimizer='adam', loss='mse')

mlp_history = mlp_model.fit(X, y , epochs=200, verbose=0)

#### Let's predict some values

In [66]:
x_inputs = np.array([70,80,90])
x_inputs = x_inputs.reshape((1, n_steps))

yhat = mlp_model.predict(x_inputs)

# Predictions of the model
print(x_inputs, yhat)

[[70 80 90]] [[108.84377]]


## Convolutional Neural Network (CNN)

In [67]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import MaxPooling1D

### 1. Data preparation

In [68]:
sequence = list()
for i in range(10,100,10):
    sequence.append(i)

n_steps = 3
n_features = 1
X, y = split_sequence(sequence, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


### 2. CNN Model

In [69]:
cnn_model = Sequential()
cnn_model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(50, activation='relu'))
cnn_model.add(Dense(1))
cnn_model.compile(optimizer='adam', loss='mse')

In [70]:
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [71]:
cnn_model.fit(X, y, epochs=1000, verbose=0)

In [77]:
x_inputs = np.array([70,80,90])
x_inputs = x_inputs.reshape((1, n_steps, n_features))

yhat = cnn_model.predict(x_inputs)
print(np.array(x_inputs), yhat)

[[[70]
  [80]
  [90]]] [[102.05795]]
