In [1]:
import numpy as np

In [30]:
def split_sequence (sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        #find the end of the pattern
        end_ix = i + n_steps
        #check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
#         return np.array(X) , np.array(y)

In [36]:
series = np.array([1,2,3,4,5,6,7,8,9])
print(series.shape)

X, y = split_sequence(series, 3)
print(X.shape, y.shape)


print('-------------------')
for i in range(len(X)):
    print(X[i], y[i])

(9,)
(6, 3) (6,)
-------------------
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
